// THESE ARE ADDRESSES SO THEY'RE INTS OF LOCATIONS IN MEMORY

const unsigned int SERVER_COUNT_ADDRESS = 33532;
const unsigned int USER_COUNT_ADDRESS = 33534;
const unsigned int MEM_START_ADDRESS = 33536;
