application: ic2s2-badgeregistration
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.app

- url: /c_templates
  static_dir: c_templates

- url: /imgs
  static_dir: imgs

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
